spring:
  application:
    name: best-process

server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}
  error:
    include-stacktrace: always
    nclude-message: always

logging:
  level:
    root: info

host: http://localhost:8080

rest:
  scoring:
    url: ${host}/scoring/score